"""
finetune.py
-----------
Fine-tunes mT5-small on your QA pairs from generate_qa.py.
Optimized for 4GB VRAM (GTX 1650 / RTX 3050).

Input:
  qa_pairs.json  — generated by generate_qa.py

Output:
  model/         — fine-tuned mT5-small ready for qa.py

Usage:
  pip install transformers datasets torch sentencepiece
  python finetune.py
"""

import os
import json
import random
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import (
    T5ForConditionalGeneration,
    AutoTokenizer,
    get_linear_schedule_with_warmup,
)


# =============================================================================
# CONFIG
# =============================================================================
QA_FILE     = r"D:\rapports_out\qa_pairs.json"
OUTPUT_DIR  = r"D:\rapports_out\model"

MODEL_NAME  = "google/mt5-small"   # ~300MB, fits in 4GB VRAM

# Training
EPOCHS      = 30       # more epochs because dataset is tiny
BATCH_SIZE  = 4        # safe for 4GB VRAM
LR          = 3e-4
MAX_SRC_LEN = 512      # context + question tokens
MAX_TGT_LEN = 64       # answer tokens
VAL_SPLIT   = 0.15     # 15% validation
SEED        = 42

random.seed(SEED)
torch.manual_seed(SEED)


# =============================================================================
# DATASET
# =============================================================================
class RapportQADataset(Dataset):
    """
    Each item = one QA pair.
    Input  format:  "question: <Q> context: <C>"
    Target format:  "<A>"
    """

    def __init__(self, pairs: list[dict], tokenizer, max_src: int, max_tgt: int):
        self.pairs     = pairs
        self.tokenizer = tokenizer
        self.max_src   = max_src
        self.max_tgt   = max_tgt

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        p = self.pairs[idx]

        # Input: question + context
        src = f"question: {p['question']} context: {p['context']}"
        tgt = p["answer"]

        src_enc = self.tokenizer(
            src,
            max_length=self.max_src,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        tgt_enc = self.tokenizer(
            tgt,
            max_length=self.max_tgt,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )

        labels = tgt_enc["input_ids"].squeeze()
        # Replace padding token id with -100 so loss ignores it
        labels[labels == self.tokenizer.pad_token_id] = -100

        return {
            "input_ids":      src_enc["input_ids"].squeeze(),
            "attention_mask": src_enc["attention_mask"].squeeze(),
            "labels":         labels,
        }


# =============================================================================
# LOAD DATA
# =============================================================================
print(f"Loading QA pairs from: {QA_FILE}")
with open(QA_FILE, "r", encoding="utf-8") as f:
    pairs = json.load(f)

print(f"  {len(pairs)} pairs loaded")

# Shuffle and split
random.shuffle(pairs)
val_size  = max(1, int(len(pairs) * VAL_SPLIT))
val_pairs = pairs[:val_size]
trn_pairs = pairs[val_size:]
print(f"  Train: {len(trn_pairs)}  |  Val: {len(val_pairs)}")


# =============================================================================
# TOKENIZER + MODEL
# =============================================================================
print(f"\nLoading {MODEL_NAME}...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model     = T5ForConditionalGeneration.from_pretrained(MODEL_NAME)

total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"  Parameters: {total_params:,} (~{total_params/1e6:.0f}M)")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"  Device: {device}")
model  = model.to(device)


# =============================================================================
# DATALOADERS
# =============================================================================
trn_ds = RapportQADataset(trn_pairs, tokenizer, MAX_SRC_LEN, MAX_TGT_LEN)
val_ds = RapportQADataset(val_pairs, tokenizer, MAX_SRC_LEN, MAX_TGT_LEN)

trn_loader = DataLoader(trn_ds, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False)


# =============================================================================
# OPTIMIZER + SCHEDULER
# =============================================================================
optimizer = torch.optim.AdamW(model.parameters(), lr=LR)

total_steps   = len(trn_loader) * EPOCHS
warmup_steps  = total_steps // 10   # 10% warmup

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=warmup_steps,
    num_training_steps=total_steps,
)


# =============================================================================
# TRAINING LOOP
# =============================================================================
print(f"\nTraining for {EPOCHS} epochs...\n")

best_val_loss = float("inf")
os.makedirs(OUTPUT_DIR, exist_ok=True)

for epoch in range(1, EPOCHS + 1):

    # ── Train ─────────────────────────────────────────────────────────────────
    model.train()
    trn_loss = 0.0

    for batch in trn_loader:
        input_ids      = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels         = batch["labels"].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels,
        )
        loss = outputs.loss

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        trn_loss += loss.item()

    trn_loss /= len(trn_loader)

    # ── Validate ───────────────────────────────────────────────────────────────
    model.eval()
    val_loss = 0.0

    with torch.no_grad():
        for batch in val_loader:
            input_ids      = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels         = batch["labels"].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels,
            )
            val_loss += outputs.loss.item()

    val_loss /= len(val_loader)

    # ── Log ───────────────────────────────────────────────────────────────────
    marker = "  ◄ best" if val_loss < best_val_loss else ""
    print(f"Epoch {epoch:3d}/{EPOCHS}  |  train loss: {trn_loss:.4f}  |  val loss: {val_loss:.4f}{marker}")

    # ── Save best model ────────────────────────────────────────────────────────
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        model.save_pretrained(OUTPUT_DIR)
        tokenizer.save_pretrained(OUTPUT_DIR)


# =============================================================================
# QUICK INFERENCE TEST
# =============================================================================
print("\n── Inference test ────────────────────────────────────────")

model.eval()

test_questions = [
    ("Quelle est la marque du véhicule ?", val_pairs[0]["context"] if val_pairs else trn_pairs[0]["context"]),
    ("Quel est le total TTC ?",            val_pairs[0]["context"] if val_pairs else trn_pairs[0]["context"]),
    ("Quels sont les dommages constatés ?", trn_pairs[0]["context"]),
]

for question, context in test_questions:
    src = f"question: {question} context: {context}"
    enc = tokenizer(
        src,
        max_length=MAX_SRC_LEN,
        truncation=True,
        return_tensors="pt",
    ).to(device)

    with torch.no_grad():
        out_ids = model.generate(
            **enc,
            max_new_tokens=64,
            num_beams=4,           # beam search for better answers
            early_stopping=True,
        )

    answer = tokenizer.decode(out_ids[0], skip_special_tokens=True)
    print(f"\n  Q: {question}")
    print(f"  A: {answer}")

print("\n──────────────────────────────────────────────────────────")
print(f"\n✅ Model saved → {OUTPUT_DIR}")
print(f"   Best val loss: {best_val_loss:.4f}")
print(f"\nNext step: qa.py  (your chatbot interface)")